### ISSUE TITLE
contribute with some icons and translate code

### ISSUE THREAD

**Issue by compsystems** [albireo77/devflowcharter#1]
Hello,

I am interested in your program, especially with improve the translated code TIBASIC (ti89, ti92p, tiv200, tinspire_cas), you are a user of these calculators?

I also want to contribute with a new translations code (QBASIC64,  HP-Prime_BASIC ) and some icons I created, please see the following application, a program editor for tibasic calculators
http://home.arcor.de/p-engels/tiedit/
Thanks

Jaime

**Comment by compsystems** [comment]
Otra imagen de un asistente para facilitar la codificación en C y similares

http://www.jaimeza.org/ComputerEngineering/images/asistentes_cpp_image00.png

**Comment by albireo77** [comment]
Hi,

I don't use TI calculators and I have never developed anything in TIBASIC. Support for TIBasic in devF was done by David Suescun.
If you would like to contribute to devF you're welcome. Generally, support for programming language in devF can be done on 2 levels: user and developer.
1. User level
You just save LanguageDefinitions\Example.xml language definition file as new file. Then you modify code generation templates in new file according to your needs.
2. Developer level
It is considered as supplement of support on user level. Here you develop some routines that generates code and add those to devF Delphi project. It gives you better control on generated code. Example for local variables: on user level, utilizing templates from XML file, you can only have single variable per line. By developing your own routine you can have declarations of all variables of the same type in one line. It is done this way for Pascal. As I said before, these routines are saved in LangTemplates directory and become part of Delphi project. If you don't have Delphi I can develop those routines following your instructions.

Regards,
Michal

**Comment by compsystems** [comment]
I think that need a window of operators and functions supported by devflowcharter, please adhere this feature, is a good idea?

Concept based on the following screenshot

http://jaimeza.org/ComputerEngineering/images/flowchart_image00.png

**Comment by albireo77** [comment]
Sorry but I think that such window is unncessary. User can enter into flowcharts whatever he wants. Native functions for given language are listed in language definition file. User functions are available at Project->Functions.

**Comment by compsystems** [comment]
for example in the c.xml, I see the following keywords, these and other could be deployed on a menu or CATALOG [control] + [space] easy to remember 
break
        char
        continue
        default
        double
        enum
        extern
        float
        int
        long
        register
        return
        short
        signed
        sizeof
        static
        struct
        switch
        typedef
        union
        unsigned
        void
        volatile
        if
        do
        while
        else
        case
        for
        goto
        const
...

in java, I always forget such combinations operators

assignment  = += -= *= /= %= >>= <<= >>>= ^= |=
conditional ?:
O logic ||
And logic &&
Or inclusive |
exclusive or (bits) ^
and (bits) &
equality == !=
relational <> => <=
shift << >> >>>
sum + -
multiplication \* / %
creation or conversion: new type(expr)
unary operators ++expr --expr +expr -expr !expr
postfix operators [] . (params) expr++ expr--
