### ISSUE TITLE
[Feature Request] Improve Comment Integration in Generated Code

### ISSUE THREAD

**Issue by ESP32DE** [albireo77/devflowcharter#7]
![grafik](https://github.com/user-attachments/assets/bb9083e0-e4c1-46fd-ad47-042dff2dcb36)

Description of the Feature Request:
I would like to point out a small detail regarding the comment integration in the generated code. Unfortunately, the comments that are inserted in the design software and marked as headers currently appear in the comments section of the generated code.

It seems that there needs to be an adjustment in the XML template area – I believe this is where the issue lies.

It would be great if we could continue to utilize this feature to make adjustments for each dialog or even just for the main template. This option to use comments as header parts is truly valuable, but unfortunately, they are currently placed in the comments section.

example
https://github.com/albireo77/devflowcharter/blob/46418285fcbc9a23d3cf8f2cdd6aab7f5586c716/LanguageDefinitions/C.xml#L136-L142

poposal: 

```

<ProgramHeaderTemplate>/*
	%s2 program generated by devFlowcharter (https://github.com/albireo77/devflowcharter)
	for %s1 project
	
*/
%s3
</ProgramHeaderTemplate>



```

How are you? I hope you are doing well! ;-) 

best wishes

[功能请求] 改进生成代码中的注释集成

功能请求的描述：
我想指出一个关于生成代码中注释集成的小细节。不幸的是，在设计软件中插入并标记为标题的注释目前出现在生成代码的注释部分。

看来在XML模板区域需要进行一些调整——我相信这就是问题所在。

如果我们能够继续利用这个功能，以便为每个对话或仅为主模板进行调整，那将是太好了。将注释用作标题部分的选项确实很有价值，但不幸的是，它们目前被放置在注释部分。

你好吗？希望你一切都好！

[Prośba o funkcję] Ulepszenie integracji komentarzy w wygenerowanym kodzie

Opis prośby o funkcję:
Chciałbym zwrócić uwagę na mały szczegół dotyczący integracji komentarzy w wygenerowanym kodzie. Niestety komentarze, które są wstawiane w oprogramowaniu projektowym i oznaczane jako nagłówki, obecnie pojawiają się w sekcji komentarzy wygenerowanego kodu.

Wydaje się, że konieczne jest dostosowanie w obszarze szablonów XML – myślę, że to tutaj tkwi problem.

Byłoby świetnie, gdybyśmy mogli nadal korzystać z tej funkcji, aby wprowadzać zmiany dla każdego dialogu lub nawet tylko dla głównego szablonu. Ta opcja używania komentarzy jako części nagłówka jest naprawdę cenna, ale niestety obecnie są one umieszczane w sekcji komentarzy.

Jak się masz? Mam nadzieję, że wszystko w porządku!

[Запрос на функцию] Улучшение интеграции комментариев в сгенерированном коде

Описание запроса на функцию:
Я хотел бы обратить внимание на небольшую деталь, касающуюся интеграции комментариев в сгенерированном коде. К сожалению, комментарии, которые вставляются в программное обеспечение для проектирования и помечаются как заголовки, в настоящее время отображаются в разделе комментариев сгенерированного кода.

Похоже, что необходимо внести изменения в область шаблонов XML – я думаю, что здесь кроется проблема.

Было бы здорово, если бы мы могли продолжать использовать эту функцию для внесения изменений для каждого диалога или даже только для основного шаблона. Эта возможность использовать комментарии в качестве заголовков действительно ценна, но, к сожалению, в настоящее время они размещаются в разделе комментариев.

Как у вас дела? Надеюсь, у вас все хорошо!

Greetings fly out to friends all over the globe
Salutations envoyées à des amis du monde entier
Saludos van a amigos de todo el mundo
Saluti volano a amici in tutto il mondo
Groeten vliegen naar vrienden over de hele wereld
Saudações vão para amigos em todo o mundo
Приветствия летят к друзьям по всему миру
问候飞向全球的朋友们
世界中の友達に挨拶が飛んでいく
تحيات تتجه إلى الأصدقاء في جميع أنحاء العالم
Selamlar dünyanın dört bir yanındaki arkadaşlara uçuyor
전 세계 친구들에게 인사가 전해집니다
दुनिया भर के दोस्तों को शुभकामनाएँ
Hälsningar flyger ut till vänner över hela världen
Hilsener flyr ut til venner over hele verden
Hilsner flyver ud til venner over hele verden
Terveisiä lentää ystäville ympäri maailmaa
Pozdravy letí k přátelům po celém světě
Üdvözletek repülnek a világ minden tájáról érkező barátokhoz 

rudi ;-)

**Comment by albireo77** [comment]
Hi Rudi,

Thanks, I am well.
It's true that by default ProgramHeaderTemplate in C.xml has %s3 placeholder inside /* */. But it's only initial suggestion. The idea behind language templates as XML files was that every user can modify and use it according to their needs. So you can too.

**Comment by ESP32DE** [comment]
Hi Michal,
thank you - yes all ok with this. Sometime i do this outside and with possible by modify the xml we are perfect flexible with this, great SWT. This can be closed - hope you are doing well the next 100 years :) too - great to read from you, Michal, best wishes :)
